"""Initial migration

Revision ID: 3a9944330afc
Revises: 
Create Date: 2021-12-31 12:00:21.695876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9944330afc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'EmployeeInfo', ['employee_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'EmployeeInfo', type_='unique')
    # ### end Alembic commands ###
